### ISSUE TITLE
Support of jsonlz4 files

### ISSUE THREAD

**Issue by blakegearin** [dearblue/ruby-extlz4#3]
Hello, I haven't been able to decompress a `.jsonlz4` file with this gem as it says my file is corrupt. I'm able to use a [Python script](https://unix.stackexchange.com/a/434882) on it successfully though.

```ruby
require 'extlz4'

filepath = 'recovery.jsonlz4'
File.exists?(filepath) # true

file = File.read(filepath)
# Python script removes the first 8 characters, so I also tried that
file2 = file[8..]

data = LZ4.block_decode(file)
data = LZ4.block_decode(file2)
# .rvm/gems/ruby-3.0.2/gems/extlz4-0.3.2/lib/extlz4.rb:285:in `decode': failed LZ4_decompress_safe - max_dest_size is too small, or data is corrupted (LZ4::Error)

max_dest_size = 1000000
dest = 'output2.json'

data = LZ4.block_decode(file, max_dest_size)
data = LZ4.block_decode(file2, max_dest_size)
# .rvm/gems/ruby-3.0.2/gems/extlz4-0.3.2/lib/extlz4.rb:285:in `decode': failed LZ4_decompress_safe - max_dest_size is too small, or data is corrupted (LZ4::Error)

decoder = LZ4.block_stream_decode
data = decoder.update(file)
data = decoder.update(file2)
# in `update': `max_dest_size' too small, or corrupt lz4'd data (LZ4::Error)

data = decoder.update(file, max_dest_size, dest)
data = decoder.update(file2, max_dest_size, dest)
# in `update': `max_dest_size' too small, or corrupt lz4'd data (LZ4::Error)

LZ4::BlockDecoder.decode(file, max_dest_size, dest)
LZ4::BlockDecoder.decode(file2, max_dest_size, dest)
# in `update': `max_dest_size' too small, or corrupt lz4'd data (LZ4::Error)

LZ4.decode_file(filepath, dest)
# .rvm/gems/ruby-3.0.2/gems/extlz4-0.3.2/lib/extlz4.rb:98:in `proc': tried to create Proc object without a block (ArgumentError)

File.open(filepath, "rb") do |f|
  LZ4.decode(f) do |lz4|
    lz4.read
  end
end
# .rvm/gems/ruby-3.0.2/gems/extlz4-0.3.2/lib/extlz4.rb:270:in `initialize': ERROR_frameType_unknown (0x000d) (LZ4::Error)
```

If this is not supported, that's fine. Wanted to make sure I'm not doing something wrong.

**Note:** This filetype is used by [Firefox for profile files](https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data#w_what-information-is-stored-in-my-profile).

**Comment by dearblue** [comment]
Hello,
As far as I can see, there are two obvious mistakes in the code presented.

```ruby
file = File.read(filepath)  # <<== (1)
# Python script removes the first 8 characters, so I also tried that
file2 = file[8..]           # <<== (2)
```

  - (1) Use `File.binread` instead of `File.read`.

  - (2) The header of jsonlz4 (mozlz4) is the first 12 **bytes** (not 8 **characters**).

    `magic_number` (8 bytes; `"mozLz40\x00"`) + `original_size` (4 bytes; little-endian)

For reference, there is an unreleased ["ruby-mozlz4"](https://github.com/dearblue/ruby-mozlz4) in my repository.
